apiVersion: v1
kind: Namespace
metadata:
  name: dep
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: dep
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxOTIuMTY4LjEwLjIwMDo1MDAwIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NllXUnRhVzQ9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: dep
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-name
    spec:
      hostNetwork: true
      containers:
      - name: app-container
        image: 192.168.10.200:5000/app
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: regcred
