apiVersion: v1
kind: Namespace
metadata:
  name: dep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: dep
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-name
    spec:
      hostNetwork: true
      containers:
      - name: app-container
        image: hello-world 
        command: 
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: regcred
